# Generated by Django 5.2.5 on 2025-08-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="travel_options",
            new_name="travel_option",
        ),
    ]
